hints = {
    'the box' : 'The beginning of the song has the sound when you wipe a mirror',
    'life is good' : 'OVO X FBGM',
    'high fashion' : 'Up style',
    'ballin\'' : 'The producer of this song is named after a condiment',
    'bop' : 'The jabbawockeez danced in the music video of this song',
    'woah' : 'A word you say when something amazes you',
    'dreams and nightmares' : 'The philly anthem',
    'dior' : 'Woo',
    'yummy' : 'A word to describe your food',
    'don\'t start now' : 'ABC',
    'falling' : 'This song became viral due to the app Tik Tok',
    'blinding lights' : 'Too bright',
    'no guidance' : 'Both artist in the song has had a relationship with Rihanna',
    'don\'t' : 'You must time it perfectly to say the title of this song during the song.',
    'exchange' : 'Swap',
    'get you' : 'This song has now avaible hint, sorry.',
    'thinkin bout you' : 'Channel Orange',
    'playing games' : 'Currently you are doing what?',
    'after hours' : 'Late at night',
    'i hope' : 'This song has now avaible hint, sorry.',
    '10,000 hours' : 'An amount of time.',
    'better together' : 'This song has now avaible hint, sorry.',
    'tennesee whiskey' : 'This is an alcholic beverage.',
    'speechless' : 'No words',
    'whiskey glasses' : 'An alcholic drink + an accessory you wear to block the sun from your eyes.',
    'she got the best of me' : 'This song has now avaible hint, sorry.',
    'roxanne' : 'This song\'s popularity is due to Tik Tok',
    'memories' : 'Looking back past events.',
    'say so' : 'This song got popular due to a Tik Tok dance.',
    'bad guy' : 'A gentleman that is not good.',
    'senorita' : 'The word for Ms. in spanish.',
    'uptown funk' : 'Based on disco type music.',
    'closer' : 'Near',
    'sicko mode' : 'AstroWorld',
    'god\'s plan' : 'The music video of this song was an artists giving people a lot of money.',
    'sweet home alabama' : 'The song\'s name contains a southern state.',
    'beautiful crazy' : 'Pretty psycho',
    'homesick' : 'When you are missing the place you are from.',
    'boo\'d up' : 'When you are in a relationship',
    'drunk in love' : 'Infatuated'
}