hints = {
    'the box' : 'The beginning of the song has the sound when you wipe a mirror',
    'life is good' : 'OVO X FBGM',
    'high fashion' : 'Up style',
    'ballin\'' : 'The producer of this song is named after a condiment',
    'bop' : 'The jabbawockeez danced in the music video of this song',
    'woah' : 'A word you say when something amazes you',
    'dreams and nightmares' : 'The philly anthem',
    'dior' : 'Woo',
    'yummy' : 'A word to describe your food',
    'don\'nt start now' : 'ABC',
    'falling' : 'This song became viral due to the app Tik Tok',
    'blinding lights' : 'Too bright',
    'no guidance' : 'Both artist in the song has had a relationship with Rihanna',
    'don\'t' : 'You must time it perfectly to say the title of this song during the song.',
    'exchange' : 'Swap',
    'get you' : '',
    'thinkin bout you' : 'Channel Orange',
    'playing games' : 'Currently you are doing what?',
    'after hours' : 'Late at night',
    'i hope' : '',
    '10,000 hours' : 'An amount of time.',
    'better together' : '',
    'tennesee whiskey' : 'This is an alcholic beverage.',
    'speechless' : 'No words',
    'whiskey glasses' : '',
    
}